### ISSUE TITLE
To score or not to score.  And if so, how?

### ISSUE THREAD

**Issue by nathenharvey** [chef-cookbooks/cookbook-quality-metrics-rfc#20]
As we think about this system there has been a lot of debate about scoring each quality metric and whether or not to generate and show some sort of aggregate or composite metric.

This issue is the appropriate place to have the discussion and debate about how scoring should work.

Some proposed options:
- Only have pass / fail scores.  Either the cookbook adheres to the metric or it does not.
- Balance the positive and negative score (e.g., the negative points for a metric may not be greater than twice the absolute value of the positive points available)

Other options and suggestions are encouraged in this issue.

**Comment by nathenharvey** [comment]
We could start by saying that metrics can only have -5, -3, -1, 0, 1, 3, or 5 as their scores and see how the data on the first set of metrics look.

**Comment by miketheman** [comment]
I'm personally anti-score, as it applies a set number, vs a measurement of usability.
Here's a link to the original RFC thread where the topic started, no point in duplicating the details. https://github.com/chef/chef-rfc/pull/147#issuecomment-139583084

**Comment by jjasghar** [comment]
Its good to have this being thought about, but honestly i'm more anti-score until we have a framework. It's very possible that the point methodology and the total points will change over time. I like the idea of thinking about it, discussing it, but we should officially say "TBD" for everything.  my .02 :metal:

**Comment by irabinovitch** [comment]
My 0.02 would be to punt on the scoring system/letter grading initially and get started with making the listing of qualities as mentioned in https://github.com/chef/chef-rfc/pull/147#issuecomment-141169103 easily visible.  We then take those qualities and make them appear as tags or searchable facets in directories like supermarket.  This way rather than searching for Apache HTTPD, I can ask supermarket to  "show me all apache cookbooks with test coverage over X, and that are used by more than 10 people".

As we define more qualities overtime and better understand their interactions, we can probably get to the point of distilling that down into a restaurant / food inspector style letter grade rather than a numeric score.  Until then we have at least made the leading quality indicators and common smells visible.  

If theres controversy over what an A grade is comprised of, consider allowing individual users to customize which of these metrics go into their letter grade when they browse supermarket; similar to the optout (and soon to be added optin) features being discussed for foodcritic.

**Comment by nathenharvey** [comment]
we've decided to delay scoring for now.  let's get the rules in place, start gathering data, and then decide if/how we score.
